### ISSUE TITLE
Enable sending SMS via Clickatell

### ISSUE THREAD

**Issue by rufer7** [rufer7/swisscom-sms-api-client#16]
[Clikcatell Bulk SMS Gateway](https://www.clickatell.com/)

**Comment by dfch** [comment]
there is a simple implementation, that you might use a base for further development in the [Graylog Clickatell AlarmCallback Plugin](https://github.com/dfch/biz.dfch.j.graylog.plugin.alarm.clickatell/tree/master/src/main/java/biz/dfch/j/clickatell)

**Comment by rufer7** [comment]
The clickatell sms client will be implemented as a separate project

Reasons:
* The response object (CommunicationWrapper) does not match the response object of clickatell because it's swisscom sms-api specific
* The artifact is deployed to maven central with swisscom in its name
